<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>PowerSound</AssemblyName>
    <RootNamespace>PowerSound</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Installer\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Sounds\*.wav" />
  </ItemGroup>
</Project>
